### PR TITLE
Add client protobuf and Go code

### PR DESCRIPTION
**Pull request by rdner**
The current API is copied from https://github.com/elastic/elastic-agent-shipper/pull/69

CI is onboarded following this https://github.com/elastic/observability-robots/blob/main/docs/teams/ci/ci-onboarding.md

~~At the moment `mage update` will replace license headers even in excluded files, therefore `mage check` will always fail and the CI build would fail. This is due to a bug in the licenser and will be fixed by https://github.com/elastic/go-licenser/pull/47~~

Related to https://github.com/elastic/elastic-agent-shipper/issues/64

### CODE REVIEW

**Comment by cmacknz** [comment]
1. Add a CODEOWNERS file: https://github.com/elastic/elastic-agent-shipper/blob/main/.github/CODEOWNERS
2. Add a license file: https://github.com/elastic/elastic-agent-shipper/blob/main/LICENSE.txt

**Comment by rdner** [comment]
@cmacknz done

**Review by cmacknz — APPROVED** [review]
LGTM, we could also add a CHANGELOG I suppose.

**Comment by rdner** [comment]
@cmacknz AFAIK we add changelog only for things versioned with the stack and for document generation, this elastic-agent-client does not have it either https://github.com/elastic/elastic-agent-client/

**Pull request merged**
